[package]
name = "pixmap"
version = "0.1.0"
description = "A simple premultiplied RGBA8 pixmap type shared across Vello crates."
categories = ["rendering", "graphics"]
keywords = ["2d", "vector-graphics"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
all-features = true
# There are no platform specific docs.
default-target = "x86_64-unknown-linux-gnu"
targets = []

[dependencies]
bytemuck = { workspace = true }
peniko = { workspace = true, features = ["bytemuck"] }
png = { workspace = true, optional = true }

[features]
# If adding new features, also document in `src/lib.rs`
default = ["std", "png"]
# Get floating point functions from the standard library (likely using your target's libc).
std = ["peniko/std"]
# Allow loading Pixmap from PNG images.
png = ["std", "dep:png"]

[lints]
workspace = true
